name: Deploy v10 to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'v10/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            v10/lib/package-lock.json
            v10/app/package-lock.json

      - name: Install morse-engine dependencies
        run: |
          cd v10/lib
          npm ci

      - name: Build morse-engine
        run: |
          cd v10/lib
          npm run build

      - name: Install app dependencies
        run: |
          cd v10/app
          npm ci

      - name: Build app
        run: |
          cd v10/app
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: v10/app/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
