name: E2E Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  e2e-test:
    name: E2E Tests on Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: v10/app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'v10/app/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install chromium --with-deps

      - name: Run debug E2E tests
        run: npx playwright test e2e/debug.spec.ts --project=chromium
        continue-on-error: true

      - name: Run all E2E tests
        run: npm run test:e2e

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: v10/app/playwright-report/
          retention-days: 30
